# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-16 22:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make_of_vehicle', models.CharField(max_length=50)),
                ('type_of_risk', models.CharField(max_length=50)),
                ('cubic_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_number', models.CharField(max_length=50)),
                ('chassis', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('number_of_seats', models.IntegerField()),
                ('license_issued_year', models.CharField(max_length=4)),
                ('insurance_type', models.CharField(max_length=50)),
                ('insurance_payment_due', models.IntegerField(default=333, editable=False, null=True)),
            ],
        ),
    ]
