# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-18 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculateInsurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='highlighted',
            field=models.TextField(null=True),
        ),
    ]
