# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-12 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculateInsurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='chassis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='cubic_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
