# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-12 15:45
from __future__ import unicode_literals

import calculateInsurance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculateInsurance', '0002_auto_20180612_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='insurance',
            field=models.IntegerField(default=calculateInsurance.models.premiumForTaxiThirdParty, editable=False),
        ),
    ]
