# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-12 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculateInsurance', '0004_auto_20180612_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='insurance_type',
            field=models.CharField(max_length=50),
        ),
    ]
