# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-12 18:40
from __future__ import unicode_literals

import calculateInsurance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculateInsurance', '0005_auto_20180612_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='insurance_payment_due',
            field=models.IntegerField(default=calculateInsurance.models.mainPremiumFunction, editable=False, null=True),
        ),
    ]
