# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-13 10:33
from __future__ import unicode_literals

import calculateInsurance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculateInsurance', '0007_auto_20180613_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='insurance_payment_due',
            field=models.IntegerField(default=calculateInsurance.models.mainPremiumFunction, editable=False, null=True),
        ),
    ]
